### ISSUE TITLE
mmcsd0s2a failed with error 19

### ISSUE THREAD

**Issue by MoritzFago** [hughobrien/zfs-remote-mirror#2] opened 2016-04-19 17:14 UTC
I built a image based on your howto, but changed to 10.3 because it is the latest available production release. I also enabled inet6, because i need it. This is also why i can't just use your image.
Hopefully you can help me. I am currently stuck at a mountroot> promt

**Comment by hughobrien** [comment] 2016-04-21 01:25
Best bet is to reduce as many error sources as possible - try following the guide as is to see if it works at all for your setup (crouton may have updated). If it does try enabling inet6, and if that works then go up to 10.3. I haven't built a 10.3 yet so there may be some changes necessary.

Let me know which step fails and I'll try and reproduce it.

**Comment by MoritzFago** [comment] 2016-04-27 21:13
to be honest i don't know what to do, because even if i just use the Standard configuration of crochet, it fails with the same reason, i tried two pis and two sdcards. I always get error 19.

**Comment by hughobrien** [comment] 2016-04-30 17:46
What model Pis are you using?
Does the provided image work at all?

I don't see any significant changes in the crochet source between then and now so I doubt it's the cause. If you can get an image to work by following the guide exactly then we have a good starting point. If that doesn't work then there may be an error in the guide itself, in that case I'm happy to go through a build with you over Skype or some such. What timezone are you in? I'm GMT.

**Comment by MoritzFago** [comment] 2016-05-16 20:29
the problem was a broken u-boot, i fixed it by using one from a official image.

**Comment by hughobrien** [comment] 2016-05-16 22:04
Glad to hear you got it sorted, I'll try and rebuild again and try a few different u-boots.

**Comment by hughobrien** [comment] 2016-05-18 12:18
[specific u-boot issue opened](https://github.com/hughobrien/zfs-remote-mirror/issues/5). Closing this one.

**Closed as completed by hughobrien** 2016-05-18 12:18 UTC
